image: markhobson/maven-chrome:jdk-11

stages:
  - Build
  - Test
  - E2E

cache:
  paths:
    - app/target/
    - common/target/
    - domain/target/
    - external-system-connector/target/
    - services/target/
    - rest/target/

compile:
  allow_failure: false
  stage: Build
  only:
    - master
    - zks
  when: always
  script:
    - mvn clean compile

unit tests:
  allow_failure: false
  stage: Test
  only:
    - master
    - zks
  when: on_success
  script:
    - mvn -P unit test

integration tests:
  allow_failure: false
  stage: Test
  only:
    - master
    - zks
  when: on_success
  script:
    - mvn -P integration test

end to end tests:
  allow_failure: false
  stage: E2E
  only:
    - master
    - zks
  when: on_success
  script:
    - mvn verify -Dheadless=true


