image: cvutczm/maven3_jdk11_cs_locale_ci:latest

stages:
  - Build
  - Test

cache:
  paths:
    - app/target/
    - common/target/
    - domain/target/
    - external-system-connector/target/
    - services/target/
    - rest/target/

compile:
  allow_failure: false
  stage: Build
  only:
    - master
  when: always
  script:
    - mvn clean compile

unit tests:
  allow_failure: false
  stage: Test
  only:
    - master
  when: on_success
  script:
    - mvn -P unit test

integration tests:
  allow_failure: false
  stage: Test
  only:
    - master
  when: on_success
  script:
    - mvn -P integration test


